[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "logiclayer-app"
version = "0.1.0"
description = "A LogicLayer-based webapp."
requires-python = ">=3.12"
dynamic = ["classifiers"]
readme = "README.md"
authors = [
  {name = "Francisco Abarzua", email = "francisco@datawheel.us"},
  {name = "Samuel Osorio", email = "samuel@datawheel.us"},
]
license = { text = "Proprietary" }
dependencies = [
    "asgi-correlation-id>=4.3.4",
    "logiclayer>=0.4.4",
    "logiclayer-complexity>=0.6.13",
    "tesseract-olap[clickhouse]>=0.18.8",
    "uvicorn>=0.34.2",
]

[dependency-groups]
dev = [
    "uvicorn[standard]>=0.34.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/project"]

[tool.pyright]
pythonVersion = "3.12"
venvPath = "."
venv = ".venv"
